name: CI – Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'flutter_app/**'

jobs:
  build:
    name: Build & Package
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download trained model
        uses: actions/download-artifact@v3
        with:
          name: model-files
          path: train/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'

      - name: Install Flutter dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Copy TFLite model into assets
        run: |
          mkdir -p flutter_app/assets
          cp train/model.tflite flutter_app/assets/model.tflite

      - name: Build release APK
        working-directory: flutter_app
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: crypto_signal_app.apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
