name: CI – Train, Convert & Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  train:
    name: 🏋️‍♂️ Train & TFLite
    runs-on: ubuntu-latest
    outputs:
      tflite-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install train dependencies
        run: pip install -r train/requirements.txt

      - name: Run training & export TFLite
        env:
          BINANCE_API_KEY:    ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          PROXY_URL:          ${{ secrets.PROXY_URL }}
        run: |
          python train/train.py

      - name: Upload TFLite model
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: model-tflite
          path: model.tflite

  build:
    name: 📱 Build Flutter APK
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download TFLite model
        uses: actions/download-artifact@v3
        with:
          name: model-tflite
          path: flutter_app/assets

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'

      - name: Install Flutter dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Build release APK
        working-directory: flutter_app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: crypto_signal_app.apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
