name: Download Historical Data (Split)

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  download-part1:
    name: Download Years 4→2 ago
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: chmod +x download_data_range.sh

      - run: |
          START=$(date -I -d "4 years ago")
          END=$(date -I -d "2 years ago")
          ./download_data_range.sh part1 "$START" "$END"

      - run: zip -r part1_zips.zip historical/part1

      - name: Upload artifact part1
        uses: actions/upload-artifact@v2
        with:
          name: historical-part1
          path: part1_zips.zip

  download-part2:
    name: Download Years 2→yesterday
    needs: download-part1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: chmod +x download_data_range.sh

      - run: |
          START=$(date -I -d "2 years ago")
          END=$(date -I -d "yesterday")
          ./download_data_range.sh part2 "$START" "$END"

      - run: zip -r part2_zips.zip historical/part2

      - name: Upload artifact part2
        uses: actions/upload-artifact@v2
        with:
          name: historical-part2
          path: part2_zips.zip
