name: 🛠️ Update BookDepth Features

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch: {}

jobs:
  update-bookdepth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas scikit-learn pyarrow parquet-tools

      - name: Update bookDepth features
        run: python update_bookDepth_features.py

      - name: Smoke-Test bookDepth
        run: |
          for FILE in features/bookDepth/*/*.parquet; do
            # Schema-Check via inspect
            parquet-tools inspect "$FILE" \
              | grep -q "notional_imbalance_roll_7d" \
              || (echo "Missing notional_imbalance_roll_7d in $FILE" && exit 1)
            parquet-tools inspect "$FILE" \
              | grep -q "kyle_lambda" \
              || (echo "Missing kyle_lambda in $FILE" && exit 1)
            # Header-Check via csv
            parquet-tools csv "$FILE" \
              | head -n1 \
              | grep -q "has_notional_imbalance_roll_7d" \
              || (echo "Missing has_notional_imbalance_roll_7d in $FILE" && exit 1)
          done
