name: 🛠️ Update BookDepth Features

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch: {}

jobs:
  update-bookdepth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn pyarrow parquet-tools EndBug/add-and-commit

      - name: Update bookDepth features
        run: python update_bookDepth_features.py

      - name: List updated columns for merged files
        run: |
          for F in features/bookDepth/*/*_to_*.parquet; do
            echo "---- $F ----"
            python -c "import pandas as pd; df = pd.read_parquet('$F'); print(df.columns.tolist())"
          done

      - name: Smoke-Test bookDepth
        run: |
          for FILE in features/bookDepth/*/*_to_*.parquet; do
            parquet-tools inspect "$FILE" \
              | grep -q "notional_imbalance_roll_7d" \
              || (echo "Missing notional_imbalance_roll_7d in $FILE" && exit 1)
            parquet-tools inspect "$FILE" \
              | grep -q "has_notional_imbalance_roll_7d" \
              || (echo "Missing has_notional_imbalance_roll_7d in $FILE" && exit 1)
            parquet-tools inspect "$FILE" \
              | grep -q "kyle_lambda" \
              || (echo "Missing kyle_lambda in $FILE" && exit 1)
          done

      - name: Commit & Push updated Parquets
        uses: EndBug/add-and-commit@v9
        with:
          add: 'features/bookDepth/**/*.parquet'
          message: 'chore: bookDepth – rolling & microstructure features'
          author_name: ghactions
          author_email: actions@github.com
