# .github/workflows/funding_features.yml
name: Extract Funding Features

on:
  workflow_dispatch:

jobs:
  extract:
    name: Extract ${{ matrix.symbol }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symbol: [BTCUSDT, ETHUSDT, BNBUSDT, XRPUSDT, SOLUSDT, ENAUSDT]

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install -r train/requirements.txt

      - name: Download Funding- & Premium-Index-Daten
        shell: bash
        run: |
          # … (unverändert) …

      - name: Funding-Extraktor ausführen
        env:
          SYMBOL: ${{ matrix.symbol }}
        run: python extract_funding_features.py

      - name: Smoke Test
        run: |
          # … (unverändert) …

      - name: Parquet für Artifact aufbereiten
        run: |
          cp features/funding/${{ matrix.symbol }}-funding-features.parquet \
             ${{ matrix.symbol }}-funding.parquet

      - name: Parquet als Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: funding-${{ matrix.symbol }}
          path: ${{ matrix.symbol }}-funding.parquet

  push:
    name: Commit & Push aller Funding-Parquets
    needs: extract
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken (mit Push-Rechten)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Alle Funding-Artifacts herunterladen
        uses: actions/download-artifact@v4
        # lädt alle artifacts unter ./ funding-<SYMBOL>/
        with:
          path: artifacts

      - name: Artefakte in features/funding kopieren
        shell: bash
        run: |
          mkdir -p features/funding
          # jedes Unterverzeichnis artifacts/funding-<SYM> enthält <SYM>-funding.parquet
          for DIR in artifacts/funding-*; do
            SYM=${DIR#artifacts/funding-}
            PARQ="$DIR/${SYM}-funding.parquet"
            if [ -f "$PARQ" ]; then
              mv "$PARQ" "features/funding/${SYM}-funding-features.parquet"
            else
              echo "Warnung: Parquet in $DIR nicht gefunden"
            fi
          done

      - name: Commit & Push (einziger Push)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase --autostash
          git add features/funding/*.parquet
          if ! git diff --cached --quiet; then
            git commit -m "chore(funding): update alle Symbole"
            git push
          else
            echo "Keine Änderungen"
          fi
