name: 🔟⏰✅💰Funding Features Incremental

on:
  schedule:
    # Nur am 20. jeden Monats um 02:00 UTC
    - cron: '0 2 20 * *'
  workflow_dispatch:
    inputs:
      start-date:
        description: 'Startdatum (YYYY-MM), optional'
        required: false
      end-date:
        description: 'Enddatum (YYYY-MM), optional'
        required: false

jobs:
  funding_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symbol: [BTCUSDT, ETHUSDT, BNBUSDT, XRPUSDT, SOLUSDT, ENAUSDT]
      max-parallel: 1
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn pyarrow

      - name: Run Funding pipeline
        run: |
          CMD="python scripts/daily_funding_pipeline.py --symbol ${{ matrix.symbol }}"
          if [[ "${{ github.event.inputs.start-date }}" != "" && "${{ github.event.inputs.end-date }}" != "" ]]; then
            CMD="$CMD --start-date ${{ github.event.inputs.start-date }} --end-date ${{ github.event.inputs.end-date }}"
          fi
          echo ">> $CMD"
          $CMD

      # … hier ggf. Smoke-Test …

      - name: Commit & Push updated Funding-Parquets
        shell: bash
        run: |
          git fetch origin main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          SYMBOL=${{ matrix.symbol }}
          FEAT_PATH="features/funding"
          git add $FEAT_PATH/${SYMBOL}-funding-features-*.parquet

          if ! git diff --cached --quiet; then
            if [[ -n "${{ github.event.inputs.start-date }}" && -n "${{ github.event.inputs.end-date }}" ]]; then
              MSG="♻️ Funding $SYMBOL historical ${{ github.event.inputs.start-date }}_to_${{ github.event.inputs.end-date }}"
            else
              MSG="♻️ Funding $SYMBOL daily $(date -I -d 'yesterday')"
            fi
            git commit -m "$MSG"
            git pull --rebase --autostash origin main
            git push --force-with-lease origin HEAD:main
          else
            echo "✔️ Keine Änderungen für $SYMBOL"
          fi
