name: 🔀 Merge BookDepth Parquets

on:
  workflow_dispatch: {}

jobs:
  merge-bookdepth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas pyarrow

      - name: Merge bookDepth Parquets
        run: python merge_bookDepth_features.py

      - name: Commit & Push merged bookDepth files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'features/bookDepth/**/*.parquet'
          message: 'chore: merge bookDepth feature Parquets per symbol'
          author_name: ghactions
          author_email: actions@github.com
