name: CI – Train & Convert Model

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'train/**'

jobs:
  train:
    name: Train & Convert
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install training dependencies
        run: pip install -r train/requirements.txt

      - name: Run training script
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: python train/train.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-files
          path: |
            model.keras
            scaler.pkl
            model.tflite
