name: Train & Convert Model
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with: python-version: '3.10'

    - name: Install train deps
      run: pip install -r train/requirements.txt

    - name: Run training
      run: python train/train.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-files
        path: |
          model.keras
          scaler.pkl
          model.tflite
